plugins {
    // https://github.com/SpongePowered/VanillaGradle
    id 'org.spongepowered.gradle.vanilla' version '0.2.2' apply false

    // https://fabricmc.net/develop
    id 'fabric-loom' version '1.12-SNAPSHOT' apply false

    // https://projects.neoforged.net/neoforged/moddevgradle
    id 'net.neoforged.moddev' version '2.0.107' apply false

    // https://files.minecraftforge.net/net/minecraftforge/gradle/ForgeGradle
    id 'net.minecraftforge.gradle' version '[6.0,6.2)' apply false
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT' apply false
}

allprojects {
    repositories {
        gradlePluginPortal()
        mavenCentral()

        exclusiveContent {
            forRepository {
                maven {
                    name = 'ParchmentMC'
                    url = 'https://maven.parchmentmc.org'
                }
            }
            filter {
                includeGroupAndSubgroups 'org.parchmentmc.data'
            }
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = 'Modrinth'
                    url = 'https://api.modrinth.com/maven'
                }
            }
            filter {
                includeGroup 'maven.modrinth'
            }
        }

        exclusiveContent {
            forRepository {
                maven {
                    name = 'CurseMaven'
                    url = 'https://cursemaven.com'
                }
            }
            filter {
                includeGroup 'curse.maven'
            }
        }
    }
}
