plugins {
    // https://github.com/SpongePowered/VanillaGradle
    id 'org.spongepowered.gradle.vanilla' version '0.2.2' apply false

    // https://fabricmc.net/develop
    id 'fabric-loom' version '1.11-SNAPSHOT' apply false

    // https://projects.neoforged.net/neoforged/moddevgradle
    id 'net.neoforged.moddev.legacyforge' version '2.0.77' apply false

    // https://files.minecraftforge.net/net/minecraftforge/gradle/ForgeGradle
    id 'net.minecraftforge.gradle' version '[6.0,6.2)' apply false
    id 'org.spongepowered.mixin' version '0.7-SNAPSHOT' apply false
}

allprojects {
    repositories {
        mavenCentral()

        maven {
            name = 'ParchmentMC'
            url = 'https://maven.parchmentmc.org/'
        }
    }
}
