plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

dependencies {
    compileOnly "maven.modrinth:spectrum:${neoforge_spectrum_version}"
    compileOnly "maven.modrinth:field-guide:${neoforge_field_guide_version}"
}

neoForge {
    version = neoforge_version

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        client {
            client()
            gameDirectory = file('runs/client')
        }
        server {
            server()
            gameDirectory = file('runs/server')
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'
